### ISSUE TITLE
Screen share Feature

### ISSUE THREAD

**Issue by Mattral** [zoom/videosdk-web-helloworld#8]
Hello, may I ask how can I add screen share feature in this app?
Thank you for this quick start. I want to try adding and make a pull request.

**Comment by EkaanshArora** [comment]
Hi @Mattral the aim of this demo is to have a very simple "hello-world" app.
To add screen sharing, you can visit our docs: https://developers.zoom.us/docs/video-sdk/web/share/. Happy to help at our developer forum if you have questions: https://devforum.zoom.us/c/video-sdk/55

**Comment by Mattral** [comment]
Thank you
